### ISSUE TITLE
Peer Review 3

### ISSUE THREAD

**Issue by j-schaub** [STAT545-UBC-students/hw03-shreeramsenthi#1]
@shreeramsenthi

**Evaluation** (scale: poor – good – great)
Coding Style – great
Coding Strategy – great
Presentation: Graphs – great
Presentation: Tables – great
Achievement, creativity – great
Ease of Access – great

**Comments**
1.	If you are interested in making your tables a bit more presentable, you can call `col.names` and write proper names for your columns. Ex:
`data %>%
kable(col.names=c(“Name 1”, “Name 2”, etc…))`
2.	The plot points and text came out a bit small and difficult to read
3.	The approach to the questions was very creative, I learned about different ways to visualize data

Overall well done!

**Comment by shreeramsenthi** [comment]
Oh hey Jessica, I didn't know you were in this course too. Thanks for the feedback and the comments, especially about the col names. I figured it would be an option but was too lazy to dig around for it. Thanks!

Cheers,
Shree
