### ISSUE TITLE
Peer Review 03

### ISSUE THREAD

**Issue by lsloboda** [STAT545-UBC-students/hw03-shreeramsenthi#2]
Peer-Review HW-03 for shreeramsenthi
----------------------------------------------------
Topic                       | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style**            | :heavy_check_mark: |  |  |
**Coding strategy**         | :heavy_check_mark: |  |  |
**Presentation: graphs**    | :heavy_check_mark: |  |  |
**Presentation: tables**    | :heavy_check_mark: |   |  |
**Achievement, creativity** | :heavy_check_mark: |  |  |
**Ease of access**          | :heavy_check_mark: |  |  |

**Remarks:**
- *I appreciated the explanation that you gave at the beginning of every task. It helped to provide context for the code and figures that followed and also showed your knowledge of statistics.*
- *Nice use of kables to make the graphs more presentable. You can also modify the column names of your tables as an additional improvement:* ``` {r} data %>% kable(col.names=c(“Name 1”, “Name 2”, etc…)) ```
- *The complexity of your graphs showcases your knowledge of R. For example, the use of brackets along the x-axis is a nice aesthetic touch - I learned something! I also liked how you customized the theme.*
- *Code is well-commented and easy to follow. Tasks are clearly identified and all required components are present.*

**Comment by shreeramsenthi** [comment]
Thanks for the kind comments Laura! I'll be sure to add column names to the kables. I meant to look into it, but got lazy. Thanks!
