### ISSUE TITLE
hw03

### ISSUE THREAD

**Issue by sherrie9** [STAT545-UBC-students/hw03-shreeramsenthi#3]
- **Task 1** Excellent explored. Good choice of violin plot to look at spread. What about max and min of gdp?
- **Task 2** Excellent use of table to quantify the changes. 👍 
- **Task 3** The bench mark used is good! You also used good strategy to solve this by properly breaking down the tasks into steps. It is interesting that although overall lifeExp is increasing, the lifeExp in African that falls below bench mark is actually increasing throughout the years! I like your analysis at the end. 

Overall good effort in the hw. Extensive comments and analysis make your exploration easy to understand. You explored an interesting story at the end. 👍

**Comment by shreeramsenthi** [comment]
Thanks for the kind comments Sherrie! I also just figured out how to add max and mins to ggplots, so I'll be sure to add them in from now on. Thanks!
